[package]
name = "reselim/roact-flipper"
version = "2.1.1"
registry = "https://github.com/Cloud-Entertainment/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
Flipper = "reselim/flipper@2.0.0"