[package]
name = "reselim/roact-flipper"
version = "2.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
Roact = "roblox/roact@1.4.0"
Flipper = "reselim/flipper@2.0.0"